spring:
  web:
    resources:
      add-mappings: false

  application:
    name: auth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.139:3306/auth
    username: user
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.123.139:8761/eureka/
